export type Product = {
  id: string;
  name: string;
  category: string;
  brand: string;
  image?: string;
  availability: string;
  specifications: string[];
};

export type ProductCategory = {
  key: string;
  name: string;
  icon: string;
  description: string;
};

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    key: "laptops",
    name: "Laptops",
    icon: "Laptop",
    description: "Browse laptops for students, professionals, and businesses.",
  },
  {
    key: "desktops",
    name: "Desktops",
    icon: "Monitor",
    description: "Desktop towers, office PCs and custom build systems.",
  },
  {
    key: "monitors",
    name: "Monitors",
    icon: "Monitor",
    description: "IPS, LED, gaming and business monitors from top brands.",
  },
  {
    key: "printers",
    name: "Printers",
    icon: "Printer",
    description: "Home and office printers from Canon, Epson and HP.",
  },
  {
    key: "printer-inks-toners",
    name: "Printer Inks & Toners",
    icon: "Droplet",
    description: "Original and compatible inks, toners and printing supplies.",
  },
  {
    key: "cctv-cameras",
    name: "CCTV Cameras",
    icon: "Camera",
    description: "Bullet, dome and wireless CCTV cameras for security.",
  },
  {
    key: "dvr-nvr",
    name: "DVR/NVR",
    icon: "HardDrive",
    description: "DVR and NVR systems for CCTV recording and monitoring.",
  },
  {
    key: "networking",
    name: "Networking",
    icon: "Network",
    description: "Routers, switches, cables and wireless networking equipment.",
  },
  {
    key: "ram",
    name: "RAM",
    icon: "MemoryStick",
    description: "Desktop and laptop RAM modules from 4GB to 32GB.",
  },
  {
    key: "ssd-hdd",
    name: "SSD & HDD",
    icon: "HardDrive",
    description: "SSD and HDD storage for PCs, laptops and servers.",
  },
  {
    key: "processors",
    name: "Processors",
    icon: "Cpu",
    description: "Intel and AMD processors for desktops, gaming and workstations.",
  },
  {
    key: "motherboards",
    name: "Motherboards",
    icon: "Chip",
    description: "AM4, LGA 1200, LGA 1700 and socket-compatible motherboards.",
  },
  {
    key: "graphics-cards",
    name: "Graphics Cards",
    icon: "Cpu",
    description: "Entry-level and gaming GPUs from NVIDIA and AMD.",
  },
  {
    key: "cabinets",
    name: "Cabinets",
    icon: "Box",
    description: "Computer cabinets and IT chassis for desktop builds.",
  },
  {
    key: "smps",
    name: "SMPS",
    icon: "Zap",
    description: "Power supplies for desktops, gaming rigs and workstation builds.",
  },
  {
    key: "ups",
    name: "UPS",
    icon: "Battery",
    description: "Backup power solutions for computers, routers and offices.",
  },
  {
    key: "keyboard-mouse",
    name: "Keyboard & Mouse",
    icon: "Keyboard",
    description: "Keyboards, mice and combo kits for office and gaming use.",
  },
  {
    key: "adapters",
    name: "Adapters",
    icon: "Plug",
    description: "Power, display and connector adapters for every setup.",
  },
  {
    key: "speakers",
    name: "Speakers",
    icon: "Volume2",
    description: "Desktop and multimedia speakers with clear audio.",
  },
  {
    key: "cables-connectors",
    name: "Cables & Connectors",
    icon: "Plug",
    description: "Cables, connectors and networking accessories.",
  },
  {
    key: "memory-cards",
    name: "Memory Cards",
    icon: "SdCard",
    description: "SD and microSD cards for cameras, mobile and storage expansion.",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "acer-aspire-3-i3-13th",
    name: "Acer Aspire 3 Core i3 13th Gen",
    category: "laptops",
    brand: "Acer",
    availability: "In stock",
    specifications: ["13th Gen Intel Core i3", "8GB RAM", "512GB SSD"],
  },
  {
    id: "dell-inspiron-15-i5",
    name: "Dell Inspiron 15 Core i5",
    category: "laptops",
    brand: "Dell",
    availability: "In stock",
    specifications: ["Intel Core i5", "8GB RAM", "256GB SSD"],
  },
  {
    id: "hp-15s-ryzen-5",
    name: "HP 15s Ryzen 5",
    category: "laptops",
    brand: "HP",
    availability: "Limited stock",
    specifications: ["AMD Ryzen 5", "8GB RAM", "512GB SSD"],
  },
  {
    id: "lenovo-thinkbook-i3",
    name: "Lenovo ThinkBook Core i3",
    category: "laptops",
    brand: "Lenovo",
    availability: "In stock",
    specifications: ["Intel Core i3", "8GB RAM", "1TB HDD"],
  },
  {
    id: "custom-gaming-desktop",
    name: "Custom Gaming Desktop PC",
    category: "desktops",
    brand: "Custom Build",
    availability: "In stock",
    specifications: ["Intel Core i5", "16GB RAM", "NVIDIA GTX 1650"],
  },
  {
    id: "dell-vostro-desktop",
    name: "Dell Vostro Desktop",
    category: "desktops",
    brand: "Dell",
    availability: "In stock",
    specifications: ["Intel Core i5", "8GB RAM", "1TB HDD"],
  },
  {
    id: "hp-prodesk-400",
    name: "HP ProDesk 400",
    category: "desktops",
    brand: "HP",
    availability: "Limited stock",
    specifications: ["Intel Core i3", "4GB RAM", "256GB SSD"],
  },
  {
    id: "refurbished-office-desktop",
    name: "Refurbished Office Desktop",
    category: "desktops",
    brand: "Refurbished",
    availability: "In stock",
    specifications: ["Intel Core i5", "8GB RAM", "256GB SSD"],
  },
  {
    id: "acer-22-inch-monitor",
    name: "Acer 22-inch Monitor",
    category: "monitors",
    brand: "Acer",
    availability: "In stock",
    specifications: ["22 inch", "IPS panel", "1920x1080"],
  },
  {
    id: "dell-24-inch-monitor",
    name: "Dell 24-inch Monitor",
    category: "monitors",
    brand: "Dell",
    availability: "In stock",
    specifications: ["24 inch", "LED panel", "1080p"],
  },
  {
    id: "acer-20-inch-office-monitor",
    name: "Acer 20-inch Office Monitor",
    category: "monitors",
    brand: "Acer",
    availability: "In stock",
    specifications: ["20 inch", "TN panel", "VGA/HDMI"],
  },
  {
    id: "hp-22-inch-monitor",
    name: "HP 22-inch Monitor",
    category: "monitors",
    brand: "HP",
    availability: "Limited stock",
    specifications: ["22 inch", "IPS panel", "HDMI"],
  },
  {
    id: "epson-l3210",
    name: "Epson L3210 Printer",
    category: "printers",
    brand: "Epson",
    availability: "In stock",
    specifications: ["InkTank", "Print/Scan/Copy", "USB"],
  },
  {
    id: "canon-g2010",
    name: "Canon G2010 Printer",
    category: "printers",
    brand: "Canon",
    availability: "In stock",
    specifications: ["InkTank", "Print/Scan/Copy", "USB"],
  },
  {
    id: "hp-laserjet-1102",
    name: "HP LaserJet 1102",
    category: "printers",
    brand: "HP",
    availability: "Limited stock",
    specifications: ["Laser", "Mono", "USB"],
  },
  {
    id: "epson-l3250-wifi",
    name: "Epson L3250 WiFi Printer",
    category: "printers",
    brand: "Epson",
    availability: "In stock",
    specifications: ["WiFi", "InkTank", "Print/Scan/Copy"],
  },
  {
    id: "epson-ink-103",
    name: "Epson 103 Ink Bottle",
    category: "printer-inks-toners",
    brand: "Epson",
    availability: "In stock",
    specifications: ["Black ink", "Economy pack", "For L3210/L3250"],
  },
  {
    id: "canon-gi-790-black",
    name: "Canon GI-790 Black Ink",
    category: "printer-inks-toners",
    brand: "Canon",
    availability: "In stock",
    specifications: ["Black ink", "Original", "For G2010/G3010"],
  },
  {
    id: "hp-85a-toner",
    name: "HP 85A Toner Cartridge",
    category: "printer-inks-toners",
    brand: "HP",
    availability: "In stock",
    specifications: ["Laser toner", "Black", "For LaserJet 1102"],
  },
  {
    id: "canon-337-toner",
    name: "Canon 337 Toner Cartridge",
    category: "printer-inks-toners",
    brand: "Canon",
    availability: "Limited stock",
    specifications: ["Black toner", "Original", "For LBP6030"],
  },
  {
    id: "cp-plus-bullet-2mp",
    name: "CP Plus 2MP Bullet Camera",
    category: "cctv-cameras",
    brand: "CP Plus",
    availability: "In stock",
    specifications: ["2MP", "Bullet", "Night vision"],
  },
  {
    id: "cp-plus-dome-2mp",
    name: "CP Plus 2MP Dome Camera",
    category: "cctv-cameras",
    brand: "CP Plus",
    availability: "In stock",
    specifications: ["2MP", "Dome", "Indoor"],
  },
  {
    id: "dahua-4k-bullet",
    name: "Dahua 4K Bullet Camera",
    category: "cctv-cameras",
    brand: "Dahua",
    availability: "Limited stock",
    specifications: ["4K", "Bullet", "Weather-proof"],
  },
  {
    id: "4g-sim-cctv-camera",
    name: "4G SIM CCTV Camera",
    category: "cctv-cameras",
    brand: "Generic",
    availability: "In stock",
    specifications: ["4G LTE", "Battery backup", "Wireless"],
  },
  {
    id: "dahua-nvr-8ch",
    name: "Dahua 8-channel NVR",
    category: "dvr-nvr",
    brand: "Dahua",
    availability: "In stock",
    specifications: ["8 channels", "4K support", "HDD slot"],
  },
  {
    id: "cp-plus-16ch-nvr",
    name: "CP Plus 16-channel NVR",
    category: "dvr-nvr",
    brand: "CP Plus",
    availability: "Limited stock",
    specifications: ["16 channels", "Remote access", "PoE support"],
  },
  {
    id: "dahua-4-channel-dvr",
    name: "Dahua 4-channel DVR",
    category: "dvr-nvr",
    brand: "Dahua",
    availability: "In stock",
    specifications: ["4 channels", "H.265", "USB backup"],
  },
  {
    id: "cp-plus-4-channel-dvr",
    name: "CP Plus 4-channel DVR",
    category: "dvr-nvr",
    brand: "CP Plus",
    availability: "In stock",
    specifications: ["4 channels", "Motion alerts", "Remote view"],
  },
  {
    id: "tp-link-router",
    name: "TP-Link Router AC750",
    category: "networking",
    brand: "TP-Link",
    availability: "In stock",
    specifications: ["Dual band", "WiFi 5", "4 Ethernet ports"],
  },
  {
    id: "d-link-switch-8",
    name: "D-Link 8-port Switch",
    category: "networking",
    brand: "D-Link",
    availability: "In stock",
    specifications: ["8 ports", "Unmanaged", "Desktop design"],
  },
  {
    id: "netgear-wifi-repeater",
    name: "Netgear WiFi Repeater",
    category: "networking",
    brand: "Netgear",
    availability: "Limited stock",
    specifications: ["WiFi extender", "Dual band", "Easy setup"],
  },
  {
    id: "cat6-network-cable",
    name: "CAT6 Network Cable 10m",
    category: "networking",
    brand: "Generic",
    availability: "In stock",
    specifications: ["10 meters", "CAT6", "Shielded"],
  },
  {
    id: "kingston-8gb-ddr4",
    name: "Kingston 8GB DDR4 RAM",
    category: "ram",
    brand: "Kingston",
    availability: "In stock",
    specifications: ["8GB", "DDR4", "3200MHz"],
  },
  {
    id: "crucial-16gb-ddr4",
    name: "Crucial 16GB DDR4 RAM",
    category: "ram",
    brand: "Crucial",
    availability: "In stock",
    specifications: ["16GB", "DDR4", "2666MHz"],
  },
  {
    id: "corsair-8gb-ddr4",
    name: "Corsair 8GB DDR4 RAM",
    category: "ram",
    brand: "Corsair",
    availability: "Limited stock",
    specifications: ["8GB", "DDR4", "3000MHz"],
  },
  {
    id: "samsung-500gb-ssd",
    name: "Samsung 500GB SSD",
    category: "ssd-hdd",
    brand: "Samsung",
    availability: "In stock",
    specifications: ["500GB", "SATA SSD", "Read 520MB/s"],
  },
  {
    id: "wd-1tb-hdd",
    name: "WD 1TB HDD",
    category: "ssd-hdd",
    brand: "Western Digital",
    availability: "In stock",
    specifications: ["1TB", "7200rpm", "SATA III"],
  },
  {
    id: "intel-core-i5-12400",
    name: "Intel Core i5-12400 Processor",
    category: "processors",
    brand: "Intel",
    availability: "In stock",
    specifications: ["6 cores", "12 threads", "12th Gen"],
  },
  {
    id: "amd-ryzen-5-5600x",
    name: "AMD Ryzen 5 5600X Processor",
    category: "processors",
    brand: "AMD",
    availability: "Limited stock",
    specifications: ["6 cores", "12 threads", "Zen 3"],
  },
  {
    id: "asus-b560-motherboard",
    name: "ASUS B560 Motherboard",
    category: "motherboards",
    brand: "ASUS",
    availability: "In stock",
    specifications: ["LGA 1200", "DDR4", "M.2 support"],
  },
  {
    id: "gigabyte-b450-motherboard",
    name: "Gigabyte B450 Motherboard",
    category: "motherboards",
    brand: "Gigabyte",
    availability: "In stock",
    specifications: ["AM4", "DDR4", "PCIe 3.0"],
  },
  {
    id: "nvidia-gtx-1650",
    name: "NVIDIA GeForce GTX 1650",
    category: "graphics-cards",
    brand: "NVIDIA",
    availability: "In stock",
    specifications: ["4GB GDDR5", "Turing", "HDMI/DP"],
  },
  {
    id: "amd-rx-6500-xt",
    name: "AMD Radeon RX 6500 XT",
    category: "graphics-cards",
    brand: "AMD",
    availability: "Limited stock",
    specifications: ["4GB GDDR6", "RDNA 2", "PCIe 4.0"],
  },
  {
    id: "cooler-master-case",
    name: "Cooler Master Cabinet",
    category: "cabinets",
    brand: "Cooler Master",
    availability: "In stock",
    specifications: ["Mid Tower", "Tempered glass", "USB 3.0"],
  },
  {
    id: "corsair-rm650x-smps",
    name: "Corsair RM650x SMPS",
    category: "smps",
    brand: "Corsair",
    availability: "In stock",
    specifications: ["650W", "80+ Gold", "Modular"],
  },
  {
    id: "apc-battery-backup-ups",
    name: "APC 650VA UPS",
    category: "ups",
    brand: "APC",
    availability: "In stock",
    specifications: ["650VA", "Battery backup", "4 outlets"],
  },
  {
    id: "logitech-k120-keyboard",
    name: "Logitech K120 Keyboard",
    category: "keyboard-mouse",
    brand: "Logitech",
    availability: "In stock",
    specifications: ["Wired", "Full-size", "Spill resistant"],
  },
  {
    id: "logitech-m90-mouse",
    name: "Logitech M90 Mouse",
    category: "keyboard-mouse",
    brand: "Logitech",
    availability: "In stock",
    specifications: ["Optical", "Wired", "USB"],
  },
  {
    id: "hdmi-vga-adapter",
    name: "HDMI to VGA Adapter",
    category: "adapters",
    brand: "Generic",
    availability: "In stock",
    specifications: ["HDMI to VGA", "Plug and play", "Compact"],
  },
  {
    id: "usb-c-power-adapter",
    name: "USB-C Power Adapter",
    category: "adapters",
    brand: "Anker",
    availability: "Limited stock",
    specifications: ["45W", "USB-C", "Fast charge"],
  },
  {
    id: "creative-pebble-speaker",
    name: "Creative Pebble 2.0 Speakers",
    category: "speakers",
    brand: "Creative",
    availability: "In stock",
    specifications: ["2.0 stereo", "USB powered", "Compact"],
  },
  {
    id: "logitech-z150-speaker",
    name: "Logitech Z150 Speaker",
    category: "speakers",
    brand: "Logitech",
    availability: "In stock",
    specifications: ["2.0 stereo", "3.5mm jack", "Compact"],
  },
  {
    id: "cat6a-patch-cable",
    name: "Cat6a Patch Cable 3m",
    category: "cables-connectors",
    brand: "Belkin",
    availability: "In stock",
    specifications: ["3m", "Cat6a", "RJ45"],
  },
  {
    id: "hdmi-cable-2m",
    name: "HDMI Cable 2m",
    category: "cables-connectors",
    brand: "Generic",
    availability: "In stock",
    specifications: ["2 meters", "4K ready", "Gold plated"],
  },
  {
    id: "sandisk-ultra-64gb",
    name: "SanDisk Ultra 64GB MicroSD",
    category: "memory-cards",
    brand: "SanDisk",
    availability: "In stock",
    specifications: ["64GB", "MicroSDXC", "UHS-I"],
  },
  {
    id: "kingston-32gb-sd",
    name: "Kingston 32GB SD Card",
    category: "memory-cards",
    brand: "Kingston",
    availability: "In stock",
    specifications: ["32GB", "SDHC", "Class 10"],
  },
];
